#!/bin/bash -eux

app_name=neo4j
deb_name=neo4j-enterprise_2.0.1_all.deb
ips=54.195.240.39,54.195.240.41,54.195.240.43,54.195.240.51

deb_url=s3://bbc.people.neo4j.org/${deb_name}
deb_file=/tmp/${deb_name}
config_dir=/etc/${app_name}
service=${app_name}-service

apt() {
    apt-get --quiet --quiet "$@"
}

(
    apt update
    apt upgrade
    apt install python-pip
    pip install awscli
    aws --region=eu-west-1 s3 cp ${deb_url} ${deb_file}
    dpkg --install --force-depends ${deb_file}
    apt --fix-broken install
    sed -i'' -e "s/.*ha\.server_id.*=.*/ha.server_id=${RANDOM}/" \
        ${config_dir}/neo4j.properties
    sed -i'' -e "s/.*ha\.initial_hosts.*=.*/ha.initial_hosts=${ips}/" \
        ${config_dir}/neo4j.properties
    sed -i'' -e "s/.*org\.neo4j\.server\.webserver\.address.*=.*/org.neo4j.server.webserver.address=0.0.0.0/" \
        ${config_dir}/neo4j-server.properties
    sed -i'' -e "s/.*org\.neo4j\.server\.database\.mode.*=.*/org.neo4j.server.database.mode=HA/" \
        ${config_dir}/neo4j-server.properties
    service ${service} restart
) 2>&1 | tee /var/log/bootstrap.log
